### ISSUE TITLE
How to cite Tango

### ISSUE THREAD

**Issue by anbasile** [allenai/tango#570]
### 📚 The doc issue

It would be nice to provide a [citation file ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) to ease referencing Tango in research paper. This project definitely deserves some more love and acknowledgment.

### Suggest a potential alternative/fix

Add a `CITATION.cff` file to the root folder with the following content:

```
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
- family-names: TODO
  given-names: TODO
  orcid: TODO
title: "AI2 Tango"
version: TODO
doi: TODO
date-released: 2022-10-5
url: "https://ai2-tango.readthedocs.io"
```
